name: Integración continua

on: 
  push

jobs:
  compilar-y-ejecutar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Compilar código
        run: gcc holaMundo.c -o holaMundo

