name: Integación continua
on: push 
jobs: 
     compliar-y-ejecutar:
            runs-on: ubunto-latest
            steps: 
                  - name: Clonar el repositorio
                    uses: action/checkout@v4
                  - name: Compilar codigo
                    run: gcc holaMundo.c -o holaMundo
                 
